schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "ps1_ify"
version = "1.5.1"
name = "PS1-ify"
tagline = "Easily import all the settings to make Blender look like a PS1 game."
maintainer = "baeac <baeacbusiness@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
